<?php include('header.php');?>
    <!-- SITE CONTENT -->
    <style>
        .information_text ul {
            text-align: left;
             list-style: none;
        }
    #more {display: none;}
    .more-button {
        position: inherit !important;
        text-align: center !important;
        width: 50% !important;
        display: inline-block !important;
        float: none !important;
        margin: auto !important;
        padding: 0px !important;
        border-radius: 0px !important;
        background-color: transparent !important;
        border: 2px solid #000 !important;
        color: #000 !important;
    } 
    .more-button:hover {
        background-color: #5da6b5 !important;
        color: #fff !important;
        transition-duration: 0.5s !important;
    }
    .portfolio-single p {
        line-height: 32.5px !important;
    }
    </style>
    <div class="wrapper">

        <div class="container">
            <section class="portfolio-single type-3 top_90 row">
                <div class="col-md-8 offset-md-2 text-center">
                    <h1 class="title bottom_45 top_120">Home Cinema, Ahmedabad </h1>
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="information_text">
                                <ul class="p-0">
                                    <li><b>Location:</b> Ahmedabad</li>
                                    <li><b>Category:</b> Interior Design</li>
                                    <li><b>Status:</b> Completed</li>
                                    <li><b>Area:</b> 35 sq mts</li>
                                    <li><b>Architect:</b> Arya Architects, AHMEDABAD</li>
                                    <li><b>CQ:</b> Associate Architects</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div>
                                <p class="bottom_30 text-left">Home cinema is an intimate family space, in an existing residence of goldsmith. This space earlier was fragmented therefore a continuous inner envelope is made for a unique experience. This envelope is mapped with a pattern generated by simple algorithm. Variation of<span id="dots">...</span> <span id="more"> same pattern in 2D and 3D are used to dissolve the edges of floor, walls and ceiling.<br><br>
                                Lights are integrated by choosing specific facets. Voids are created within the facets to place equipment. Cutting and numbering each piece is precisely done on a CNC router. Assembly process demonstrates the shift from digital assembly. This is the most challenging as well as interesting aspect of the project.</span></p>
                                <button class="more-button" onclick="myFunction()" id="myBtn">Read more</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-8 offset-md-2 portfolio-images top_90 text-center">
                    <figure class="bottom_30"><img src="../images/WWA-001OverAll.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-002.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-003OverAll.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-004.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-005OverAll.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-006OverAll.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-007OverAll.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-008OverAll.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-009OverAll.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-010OverAll.jpg" alt=""></figure>
                     <figure class="bottom_30"><img src="../images/WWA-011OverAll.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-012OverAll.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-013OverAll.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/WWA-014OverAll.jpg" alt=""></figure>
                </div>

               <!-- <div class="col-md-12 portfolio-nav text-center top_90">
                    <a class="port-next" href="work-6.html">
                        <div class="nav-title">next</div>
                        <div class="next-title">Motorcycles</div>
                    </a>
                </div>-->

            </section>

        </div> <!-- cont end -->
    </div> <!-- wrapper end -->
<?php include('footer.php');?>
<script>
    function myFunction() {
      var dots = document.getElementById("dots");
      var moreText = document.getElementById("more");
      var btnText = document.getElementById("myBtn");

      if (dots.style.display === "none") {
        dots.style.display = "inline";
        btnText.innerHTML = "Read more"; 
        moreText.style.display = "none";
    } else {
        dots.style.display = "none";
        btnText.innerHTML = "Read less"; 
        moreText.style.display = "inline";
    }
}
</script>