<?php include('header.php');?>
    <!-- SITE CONTENT -->
    <div class="wrapper">

        <div class="cont">
            <section class="portfolio-single type-3 top_90 row">
                <div class="col-md-8 offset-md-2 text-center">
                    <h1 class="title top_120">Kataria Residence, Ahmedabad</h1>

                    <div class="row">
                        <div class="col-lg-4">
                            <div class="information_text">
                                <ul class="p-0">
                                    <li><b>Status:</b>Ongoing</li>
                                    <li><b>Client:</b> Dr. jalpesh Kataria </li>
                                    <li><b>Material:</b> RCC, Brick, Glass and Wood</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <!-- <div>
                                <p class="bottom_30 text-left">Home cinema is an intimate family space, in an existing residence of goldsmith. This space earlier was fragmented therefore a continuous inner envelope is made for a unique experience. This envelope is mapped with a pattern generated by simple algorithm. Variation of same pattern in 2D and 3D are used to dissolve the edges of floor, walls and ceiling.</p>
                                <p class="bottom_30 text-left">Lights are integrated by choosing specific facets. Voids are created within the facets to place equipment. Cutting and numbering each piece is precisely done on a CNC router. Assembly process demonstrates the shift from digital assembly. This is the most challenging as well as interesting aspect of the project.</p>
                            </div> -->
                        </div>
                    </div>
                </div>
            </section>

        </div> <!-- cont end -->
    </div> <!-- wrapper end -->
<?php include('footer.php');?>