<?php include('header.php');?>
    <!-- SITE CONTENT -->
     <style>
        .information_text ul {
            text-align: left;
             list-style: none;
        }
    </style>
    <div class="wrapper">

        <div class="cont">
            <section class="portfolio-single type-3 top_90 row">
                <div class="col-md-8 offset-md-2 text-center">
                    <h1 class="title bottom_30 top_120">Private Residence, Ahmedabad</h1>
                       <div class="row">
                        <div class="col-lg-4">
                            <div class="information_text">
                                <ul class="p-0">
                                    <li><b>Location:</b> Ahmedabad</li>
                                    <li><b>Category:</b> Residential architecture</li>
                                    <li><b>Status:</b> Completed</li>
                                    <li><b>Client:</b> Dr. jalpesh Kataria</li>
                                    <li><b>Material:</b> MS sheet, metal</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <!-- <div>
                                <p class="bottom_30 text-left">Home cinema is an intimate family space, in an existing residence of goldsmith. This space earlier was fragmented therefore a continuous inner envelope is made for a unique experience. This envelope is mapped with a pattern generated by simple algorithm. Variation of same pattern in 2D and 3D are used to dissolve the edges of floor, walls and ceiling.</p>
                                <p class="bottom_30 text-left">Lights are integrated by choosing specific facets. Voids are created within the facets to place equipment. Cutting and numbering each piece is precisely done on a CNC router. Assembly process demonstrates the shift from digital assembly. This is the most challenging as well as interesting aspect of the project.</p>
                            </div> -->
                        </div>
                    </div>
                </div>

                <div class="col-md-8 offset-md-2 portfolio-images top_90 text-center">
                    <figure class="bottom_30"><img src="../images/PrivateResidence.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/PrivateResidence1.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/PrivateResidence3.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/PrivateResidence4.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/PrivateResidence5.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/PrivateResidence6.jpg" alt=""></figure>
                    <figure class="bottom_30"><img src="../images/PrivateResidence7.jpg" alt=""></figure>
                </div>

              <!--  <div class="col-md-12 portfolio-nav text-center top_90">
                    <a class="port-next" href="work-8.html">
                        <div class="nav-title">next</div>
                        <div class="next-title">Racquel Natasha</div>
                    </a>
                </div>-->

            </section>

        </div> <!-- cont end -->
    </div> <!-- wrapper end -->

<?php include('footer.php');?>